 # Sources: 
 #  - https://mike42.me/blog/how-to-set-up-docker-containers-in-travis-ci
 #  - http://bencane.com/2016/01/11/using-travis-ci-to-test-docker-builds/

 # Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

install:
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d
  # Show running containers.
  - docker ps -a

script:
  # Make sure containers are all running.
  - docker ps | grep -q topac

after_script:
  - docker-compose down
  # Push containers to docker registry.